exclude: "^conda.recipe|assets|docs"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude_types: ["python", "jupyter", "shell", "gitignore"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      # Run the linter
      - id: ruff-check
        types_or: [python, pyi]
      # TODO: Enable when black and ruff format converge
      # Run the formatter
      # - id: ruff-format
      #   types_or: [python, pyi]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # notebook JSON hygiene
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # notebook code quality
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-ruff
        args: ["--fix"]
