exclude: "^conda.recipe|assets|docs"

repos:
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.2.0
    hooks:
      - id: nb-clean
        args:
          - --preserve-cell-outputs
          - --remove-empty-cells
        types: [jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude_types: ["python", "jupyter", "shell", "gitignore"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/yzhang-gh/black-nb
    rev: v0.7.0
    hooks:
      - id: black-nb

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        name: ruff-check
        types_or: [python, pyi, jupyter]
      # TODO: Enable when black and ruff format converge
      # - id: ruff-format
      #   types_or: [python, pyi]
