name: Format python code
on: 
  push:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
jobs:
  autopep8-black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: autopep8
      uses: peter-evans/autopep8@v1.0.0
      with:
        args: --recursive --in-place --aggressive --aggressive .
    - name: autoblack
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "."
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        commit_author_email: ''
        commit_author_name: AutoPEP8
        commit_message: autopep8 fix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
