name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: autopep8
      uses: peter-evans/autopep8@v1.0.0
      with:
        args: --recursive --in-place --aggressive --aggressive .
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        commit_author_email: ''
        commit_author_name: AutoPEP8
        commit_message: autopep8 fix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
